import { User } from '../types/user.types';
import { Project, ProjectMemberRole } from '../types/project.types';
import { Task, TaskPriority, TaskStatus } from '../types/task.types';
import { Label } from '../types/label.types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    username: 'nguyenvana',
    fullName: 'Nguyễn Văn A',
    email: 'vana@example.com',
    createdAt: '2026-08-01T08:00:00.000Z',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 2,
    username: 'nguyenvanb',
    fullName: 'Nguyễn Văn B',
    email: 'vanb@example.com',
    createdAt: '2026-08-05T09:30:00.000Z',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 3,
    username: 'tranthic',
    fullName: 'Trần Thị C',
    email: 'thic@example.com',
    createdAt: '2026-08-10T14:15:00.000Z',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 4,
    username: 'lequangd',
    fullName: 'Lê Quang D',
    email: 'quangd@example.com',
    createdAt: '2026-08-12T11:00:00.000Z',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 1,
    name: 'Website bán hàng',
    description: 'Xây dựng website bán hàng online đa kênh với tích hợp cổng thanh toán và quản lý đơn hàng thông minh.',
    ownerId: 1,
    createdAt: '2026-08-01T10:00:00.000Z',
    owner: INITIAL_USERS[0],
    members: [
      {
        projectId: 1,
        userId: 1,
        role: ProjectMemberRole.ADMIN,
        joinedAt: '2026-08-01T10:00:00.000Z',
        user: INITIAL_USERS[0],
      },
      {
        projectId: 1,
        userId: 2,
        role: ProjectMemberRole.MEMBER,
        joinedAt: '2026-08-02T08:30:00.000Z',
        user: INITIAL_USERS[1],
      },
      {
        projectId: 1,
        userId: 3,
        role: ProjectMemberRole.MEMBER,
        joinedAt: '2026-08-03T09:00:00.000Z',
        user: INITIAL_USERS[2],
      },
    ],
  },
  {
    id: 2,
    name: 'Mobile Banking App',
    description: 'Ứng dụng ngân hàng số bảo mật cao trên nền tảng React Native với sinh trắc học và thanh toán QR.',
    ownerId: 1,
    createdAt: '2026-08-10T14:00:00.000Z',
    owner: INITIAL_USERS[0],
    members: [
      {
        projectId: 2,
        userId: 1,
        role: ProjectMemberRole.ADMIN,
        joinedAt: '2026-08-10T14:00:00.000Z',
        user: INITIAL_USERS[0],
      },
      {
        projectId: 2,
        userId: 4,
        role: ProjectMemberRole.MEMBER,
        joinedAt: '2026-08-11T10:30:00.000Z',
        user: INITIAL_USERS[3],
      },
    ],
  },
];

export const INITIAL_LABELS: Label[] = [
  { id: 1, projectId: 1, name: 'BACKEND', colorCode: '#6366f1' },
  { id: 2, projectId: 1, name: 'BUG', colorCode: '#ef4444' },
  { id: 3, projectId: 1, name: 'FEATURE', colorCode: '#10b981' },
  { id: 4, projectId: 1, name: 'URGENT', colorCode: '#f59e0b' },
  { id: 5, projectId: 1, name: 'DATABASE', colorCode: '#8b5cf6' },
  { id: 6, projectId: 2, name: 'MOBILE', colorCode: '#06b6d4' },
  { id: 7, projectId: 2, name: 'SECURITY', colorCode: '#f43f5e' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 1,
    projectId: 1,
    title: 'Implement Login API',
    description: 'Xây dựng API đăng nhập bằng JWT bảo mật cao với mã hóa SHA-512 và xác thực người dùng.',
    status: TaskStatus.DOING,
    priority: TaskPriority.HIGH,
    dueDate: '2026-08-20T23:59:59.000Z',
    assigneeId: 2,
    orderIndex: 0,
    createdAt: '2026-08-15T08:00:00.000Z',
    assignee: INITIAL_USERS[1],
    labels: [INITIAL_LABELS[0], INITIAL_LABELS[3]], // BACKEND, URGENT
    comments: [
      {
        id: 1,
        taskId: 1,
        userId: 1,
        content: 'API đã hoàn thành phần xử lý thanh toán và token generation.',
        createdAt: '2026-08-18T10:00:00.000Z',
        user: INITIAL_USERS[0],
      },
      {
        id: 2,
        taskId: 1,
        userId: 2,
        content: 'Đã test trên môi trường development, chạy rất mượt!',
        createdAt: '2026-08-18T11:15:00.000Z',
        user: INITIAL_USERS[1],
      },
    ],
    attachments: [
      {
        id: 1,
        taskId: 1,
        uploaderId: 1,
        fileName: 'api-documentation.docx',
        fileUrl: 'https://example.com/docs/api-documentation.docx',
        uploadedAt: '2026-08-15T09:00:00.000Z',
        uploader: INITIAL_USERS[0],
      },
    ],
    activities: [
      {
        id: 1,
        taskId: 1,
        userId: 1,
        action: 'Nguyễn Văn A đã tạo Task',
        createdAt: '2026-08-15T08:00:00.000Z',
        user: INITIAL_USERS[0],
      },
      {
        id: 2,
        taskId: 1,
        userId: 1,
        action: 'Nguyễn Văn A đã giao Task cho Nguyễn Văn B',
        createdAt: '2026-08-15T08:15:00.000Z',
        user: INITIAL_USERS[0],
      },
      {
        id: 3,
        taskId: 1,
        userId: 2,
        action: 'Nguyễn Văn B đổi Priority: Medium → High',
        createdAt: '2026-08-16T09:30:00.000Z',
        user: INITIAL_USERS[1],
      },
      {
        id: 4,
        taskId: 1,
        userId: 2,
        action: 'Nguyễn Văn B đổi Status: Todo → Doing',
        createdAt: '2026-08-17T10:00:00.000Z',
        user: INITIAL_USERS[1],
      },
    ],
  },
  {
    id: 2,
    projectId: 1,
    title: 'Fix Login Bug',
    description: 'Khắc phục lỗi xác thực token khi hết hạn không trả về đúng HTTP 401 trên mobile client.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    dueDate: '2026-08-22T18:00:00.000Z',
    assigneeId: 2,
    orderIndex: 0,
    createdAt: '2026-08-16T09:00:00.000Z',
    assignee: INITIAL_USERS[1],
    labels: [INITIAL_LABELS[1], INITIAL_LABELS[3]], // BUG, URGENT
    comments: [],
    attachments: [],
    activities: [
      {
        id: 5,
        taskId: 2,
        userId: 1,
        action: 'Nguyễn Văn A đã tạo Task',
        createdAt: '2026-08-16T09:00:00.000Z',
        user: INITIAL_USERS[0],
      },
    ],
  },
  {
    id: 3,
    projectId: 1,
    title: 'Design Database Schema',
    description: 'Thiết kế ERD và viết script SQL tạo các bảng Users, Projects, Tasks, Labels, Attachments, Comments.',
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    dueDate: '2026-08-18T17:00:00.000Z',
    assigneeId: 1,
    orderIndex: 0,
    createdAt: '2026-08-12T08:00:00.000Z',
    assignee: INITIAL_USERS[0],
    labels: [INITIAL_LABELS[4]], // DATABASE
    comments: [
      {
        id: 3,
        taskId: 3,
        userId: 1,
        content: 'Đã cập nhật quan hệ ON DELETE CASCADE và indexing cho performance.',
        createdAt: '2026-08-14T15:30:00.000Z',
        user: INITIAL_USERS[0],
      },
    ],
    attachments: [
      {
        id: 2,
        taskId: 3,
        uploaderId: 1,
        fileName: 'database-design.pdf',
        fileUrl: 'https://example.com/docs/database-design.pdf',
        uploadedAt: '2026-08-13T10:00:00.000Z',
        uploader: INITIAL_USERS[0],
      },
      {
        id: 3,
        taskId: 3,
        uploaderId: 1,
        fileName: 'database-erd.png',
        fileUrl: 'https://example.com/docs/database-erd.png',
        uploadedAt: '2026-08-13T10:05:00.000Z',
        uploader: INITIAL_USERS[0],
      },
    ],
    activities: [
      {
        id: 6,
        taskId: 3,
        userId: 1,
        action: 'Nguyễn Văn A đã tạo Task',
        createdAt: '2026-08-12T08:00:00.000Z',
        user: INITIAL_USERS[0],
      },
      {
        id: 7,
        taskId: 3,
        userId: 1,
        action: 'Nguyễn Văn A đổi Status: Doing → Done',
        createdAt: '2026-08-17T16:30:00.000Z',
        user: INITIAL_USERS[0],
      },
    ],
  },
  {
    id: 4,
    projectId: 1,
    title: 'Xây dựng giao diện Kanban Board',
    description: 'Xây dựng giao diện kéo thả trực quan theo dõi tiến độ các trạng thái Todo, Doing, Done.',
    status: TaskStatus.DOING,
    priority: TaskPriority.MEDIUM,
    dueDate: '2026-08-25T12:00:00.000Z',
    assigneeId: 3,
    orderIndex: 1,
    createdAt: '2026-08-16T14:00:00.000Z',
    assignee: INITIAL_USERS[2],
    labels: [INITIAL_LABELS[2]], // FEATURE
    comments: [],
    attachments: [],
    activities: [
      {
        id: 8,
        taskId: 4,
        userId: 1,
        action: 'Nguyễn Văn A đã tạo Task và giao cho Trần Thị C',
        createdAt: '2026-08-16T14:00:00.000Z',
        user: INITIAL_USERS[0],
      },
    ],
  },
  {
    id: 5,
    projectId: 1,
    title: 'Tích hợp cổng thanh toán VNPay / Momo',
    description: 'Kết nối API thanh toán điện tử, xử lý webhook callback và cập nhật trạng thái đơn hàng.',
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    dueDate: '2026-08-30T18:00:00.000Z',
    assigneeId: 1,
    orderIndex: 1,
    createdAt: '2026-08-17T10:00:00.000Z',
    assignee: INITIAL_USERS[0],
    labels: [INITIAL_LABELS[0], INITIAL_LABELS[2]], // BACKEND, FEATURE
    comments: [],
    attachments: [],
    activities: [],
  },
];
